### ISSUE TITLE
Assignment View references the wrong graph script file

### ISSUE THREAD

**Issue by squeetus** [stevemacn/bridgesAPI#28]
Assignment.jade lines 92 and 93 are currently:

   - if (vistype == "nodelink")
        script(src = '/js/graph_multi.js')

These two lines should be: 

   - if (vistype == "nodelink")
        script(src = '/js/graph.js')

This will point single assignments requiring nodelink representation to the correct script file.

**Comment by mmehedin** [comment]
Declaring the d3 variable in the graph.js is redundant and overwrites the d3 object containing data.
